DATOS_MATERIAS = {
    "Matemáticas": {
        # Números básicos
        "1": ["2-1", "3-2", "5-4", "10÷10"],
        "2": ["8÷4", "6-4", "1+1", "4÷2", "3-1"],
        "3": ["6÷2", "1+2", "9÷3", "5-2", "4-1"],
        "4": ["2+2", "7-3", "10-6", "2×2", "8÷2"],
        "5": ["10÷2", "9-4", "15÷3", "3+2", "6-1"],
        "6": ["3×2", "12÷2", "4+2", "9-3", "7-1"],
        "7": ["14÷2", "3+4", "10-3", "8-1", "21÷3"],
        "8": ["4×2", "16÷2", "5+3", "10-2", "24÷3"],
        "9": ["3×3", "6+3", "7+2", "18÷2", "10-1"],
        "10": ["5×2", "8+2", "20÷2", "6+4", "15-5"],
        "11": ["22÷2", "6+5", "8+3", "12-1", "33÷3"],
        "12": ["4×3", "6×2", "24÷2", "8+4", "15-3"],
        "15": ["5×3", "30÷2", "10+5", "18-3", "45÷3"],
        "16": ["4×4", "32÷2", "8+8", "20-4", "48÷3"],
        "18": ["6×3", "9×2", "36÷2", "10+8", "21-3"],
        "20": ["4×5", "10×2", "40÷2", "15+5", "25-5"],
        "24": ["6×4", "8×3", "48÷2", "20+4", "30-6"],
        "25": ["5×5", "50÷2", "20+5", "30-5", "75÷3"],
        "30": ["6×5", "10×3", "60÷2", "25+5", "35-5"],
        "36": ["6×6", "9×4", "72÷2", "30+6", "40-4"],
        # Fracciones
        "1/2": ["0.5", "50%", "Mitad"],
        "1/4": ["0.25", "25%", "Cuarto"],
        "3/4": ["0.75", "75%", "Tres cuartos"],
        "1/3": ["0.33", "33%", "Tercio"],
        "2/3": ["0.66", "66%", "Dos tercios"]
    },
    "Historia": {
        # Fechas importantes
        "Descubrimiento América": ["1492", "Colón llegó", "12 de Octubre"],
        "Revolución Francesa": ["1789", "Toma de la Bastilla", "14 de Julio"],
        "Independencia Argentina": ["1810", "25 de Mayo", "Revolución Mayo"],
        "Independencia EEUU": ["1776", "4 de Julio", "Declaración"],
        "Primera Guerra Mundial": ["1914", "Gran Guerra", "1914-1918"],
        "Segunda Guerra Mundial": ["1939", "Guerra Mundial II", "1939-1945"],
        "Llegada a la Luna": ["1969", "Apollo 11", "Neil Armstrong"],
        "Caída Muro Berlín": ["1989", "9 de Noviembre", "Reunificación"],
        "Revolución Rusa": ["1917", "Octubre Rojo", "Lenin"],
        "Guerra Civil Española": ["1936", "Franco", "1936-1939"],
        "Independencia Brasil": ["1822", "7 de Septiembre", "Pedro I"],
        "Revolución Mexicana": ["1910", "Villa y Zapata", "1910-1920"],
        
        # Personajes históricos
        "Francia": ["Napoleón", "Bonaparte", "Luis XIV"],
        "Argentina": ["San Martín", "Belgrano", "Libertador"],
        "España": ["Colón", "Cristóbal Colón", "Carlos V"],
        "Estados Unidos": ["Washington", "George Washington", "Lincoln"],
        "Venezuela": ["Bolívar", "Simón Bolívar", "Libertador"],
        "Inglaterra": ["Churchill", "Winston", "Nelson"],
        "Alemania": ["Bismarck", "Otto von", "Kaiser"],
        "Italia": ["Garibaldi", "Giuseppe", "Unificador"],
        "Rusia": ["Pedro el Grande", "Catalina", "Zares"],
        "China": ["Mao", "Mao Zedong", "Emperador"],
        "Egipto": ["Cleopatra", "Faraones", "Nefertiti"],
        "Grecia": ["Alejandro", "Magno", "Pericles"],
        
        # Civilizaciones
        "Imperio Romano": ["César", "Augusto", "Coliseo"],
        "Imperio Inca": ["Machu Picchu", "Cusco", "Atahualpa"],
        "Imperio Azteca": ["Tenochtitlan", "Moctezuma", "México"],
        "Antigua Grecia": ["Atenas", "Esparta", "Filosofía"],
        "Egipto Antiguo": ["Pirámides", "Faraones", "Nilo"],
        "Imperio Maya": ["Chichen Itza", "Calendario", "Yucatán"]
    },
    "Química": {
        # Elementos químicos
        "Hidrógeno": ["H", "Elemento 1", "Más ligero"],
        "Helio": ["He", "Elemento 2", "Gas noble"],
        "Litio": ["Li", "Elemento 3", "Metal alcalino"],
        "Carbono": ["C", "Elemento 6", "Vida orgánica"],
        "Nitrógeno": ["N", "Elemento 7", "78% aire"],
        "Oxígeno": ["O", "O₂", "Elemento 8", "21% aire"],
        "Flúor": ["F", "Elemento 9", "Más electronegativo"],
        "Neón": ["Ne", "Elemento 10", "Gas noble"],
        "Sodio": ["Na", "Elemento 11", "Metal alcalino"],
        "Magnesio": ["Mg", "Elemento 12", "Clorofila"],
        "Aluminio": ["Al", "Elemento 13", "Metal ligero"],
        "Silicio": ["Si", "Elemento 14", "Semiconductores"],
        "Fósforo": ["P", "Elemento 15", "ADN"],
        "Azufre": ["S", "Elemento 16", "Amarillo"],
        "Cloro": ["Cl", "Elemento 17", "Desinfectante"],
        "Potasio": ["K", "Elemento 19", "Plátanos"],
        "Calcio": ["Ca", "Elemento 20", "Huesos"],
        "Hierro": ["Fe", "Elemento 26", "Sangre"],
        "Cobre": ["Cu", "Elemento 29", "Cables"],
        "Zinc": ["Zn", "Elemento 30", "Galvanizado"],
        "Plata": ["Ag", "Elemento 47", "Joyería"],
        "Oro": ["Au", "Elemento 79", "Precioso"],
        "Mercurio": ["Hg", "Elemento 80", "Líquido"],
        "Plomo": ["Pb", "Elemento 82", "Pesado"],
        
        # Compuestos químicos
        "Agua": ["H₂O", "Hidrógeno + Oxígeno", "Vida"],
        "Dióxido Carbono": ["CO₂", "Carbono + Oxígeno", "Respiración"],
        "Sal común": ["NaCl", "Cloruro de Sodio", "Mesa"],
        "Metano": ["CH₄", "Carbono + Hidrógeno", "Gas natural"],
        "Amoníaco": ["NH₃", "Nitrógeno + Hidrógeno", "Limpieza"],
        "Ácido sulfúrico": ["H₂SO₄", "Batería", "Corrosivo"],
        "Glucosa": ["C₆H₁₂O₆", "Azúcar", "Energía"],
        "Etanol": ["C₂H₅OH", "Alcohol", "Bebidas"],
        "Aspirina": ["C₉H₈O₄", "Medicamento", "Dolor"],
        "Cafeína": ["C₈H₁₀N₄O₂", "Estimulante", "Café"],
        "Penicilina": ["Antibiótico", "Fleming", "Medicina"],
        "Ozono": ["O₃", "Capa protectora", "UV"]
    },
    "Geografía": {
        # Capitales de América
        "Buenos Aires": ["Argentina", "Capital Argentina", "Río de la Plata"],
        "Brasilia": ["Brasil", "Capital Brasil", "Planeada"],
        "Santiago": ["Chile", "Capital Chile", "Cordillera"],
        "Lima": ["Perú", "Capital Perú", "Pacífico"],
        "Bogotá": ["Colombia", "Capital Colombia", "Altiplano"],
        "Caracas": ["Venezuela", "Capital Venezuela", "Caribe"],
        "Quito": ["Ecuador", "Capital Ecuador", "Mitad del mundo"],
        "La Paz": ["Bolivia", "Capital Bolivia", "Más alta"],
        "Asunción": ["Paraguay", "Capital Paraguay", "Río Paraguay"],
        "Montevideo": ["Uruguay", "Capital Uruguay", "Río de la Plata"],
        "Ciudad México": ["México", "Capital México", "Azteca"],
        "Ottawa": ["Canadá", "Capital Canadá", "Bilingüe"],
        "Washington": ["Estados Unidos", "Capital EEUU", "Potomac"],
        
        # Capitales de Europa
        "París": ["Francia", "Capital Francia", "Torre Eiffel"],
        "Roma": ["Italia", "Capital Italia", "Coliseo"],
        "Madrid": ["España", "Capital España", "Centro"],
        "Londres": ["Reino Unido", "Capital UK", "Big Ben"],
        "Berlín": ["Alemania", "Capital Alemania", "Muro"],
        "Viena": ["Austria", "Capital Austria", "Música"],
        "Berna": ["Suiza", "Capital Suiza", "Alpes"],
        "Ámsterdam": ["Países Bajos", "Capital Holanda", "Canales"],
        "Estocolmo": ["Suecia", "Capital Suecia", "Nobel"],
        "Oslo": ["Noruega", "Capital Noruega", "Fiordos"],
        "Copenhague": ["Dinamarca", "Capital Dinamarca", "Sirenita"],
        "Helsinki": ["Finlandia", "Capital Finlandia", "Saunas"],
        
        # Capitales de Asia y África
        "Tokio": ["Japón", "Capital Japón", "Más poblada"],
        "Pekín": ["China", "Capital China", "Ciudad Prohibida"],
        "Nueva Delhi": ["India", "Capital India", "Taj Mahal"],
        "Bangkok": ["Tailandia", "Capital Tailandia", "Templos"],
        "El Cairo": ["Egipto", "Capital Egipto", "Pirámides"],
        "Nairobi": ["Kenia", "Capital Kenia", "Safari"],
        "Ciudad del Cabo": ["Sudáfrica", "Capital Sudáfrica", "Mesa"],
        
        # Ríos importantes
        "Brasil": ["Amazonas", "Río Amazonas", "Más caudaloso"],
        "Egipto": ["Nilo", "Río Nilo", "Más largo"],
        "Estados Unidos": ["Misisipi", "Río Misisipi", "Padre de aguas"],
        "Argentina": ["Paraná", "Río Paraná", "Río de la Plata"],
        "China": ["Yangtsé", "Río Amarillo", "Dragón"],
        "India": ["Ganges", "Río sagrado", "Benarés"],
        "Europa": ["Danubio", "Río Danubio", "Vals"],
        "Rusia": ["Volga", "Río Volga", "Más largo Europa"],
        "Francia": ["Sena", "Río Sena", "París"],
        "Inglaterra": ["Támesis", "Río Támesis", "Londres"],
        
        # Montañas y cordilleras
        "Nepal": ["Everest", "Monte Everest", "Más alto"],
        "Argentina": ["Aconcagua", "Monte Aconcagua", "América"],
        "Alaska": ["McKinley", "Monte McKinley", "Norteamérica"],
        "África": ["Kilimanjaro", "Monte Kilimanjaro", "Tanzania"],
        "Europa": ["Mont Blanc", "Monte Blanco", "Alpes"],
        "Japón": ["Fuji", "Monte Fuji", "Volcán"],
        "Perú": ["Huascarán", "Cordillera Blanca", "Andes"],
        "Chile": ["Ojos del Salado", "Volcán más alto", "Andes"],
        
        # Océanos y mares
        "Pacífico": ["Más grande", "Océano mayor", "Anillo de fuego"],
        "Atlántico": ["Segundo mayor", "Océano Atlántico", "Titanic"],
        "Índico": ["Tercer mayor", "Océano Índico", "Monzones"],
        "Ártico": ["Más pequeño", "Océano Ártico", "Polo Norte"],
        "Mediterráneo": ["Mar cerrado", "Cuna civilización", "Europa-África"],
        "Caribe": ["Mar tropical", "Islas", "Piratas"],
        "Negro": ["Mar Negro", "Europa-Asia", "Bósforo"],
        "Rojo": ["Mar Rojo", "Moisés", "Coral"]
    }
}