# Configuración de ventana
ANCHO_VENTANA = 1024
ALTO_VENTANA = 768
FPS = 60
TITULO_JUEGO = "Cartas en Juego"

# Configuración del modo Parejas
PAREJAS_FILAS = 2
PAREJAS_COLUMNAS = 3
PAREJAS_TIEMPO_CRONOMETRO = 30
PAREJAS_NIVELES_MAX = 3
PAREJAS_PUNTOS_ACIERTO = 10
PAREJAS_PUNTOS_ERROR = -10

# Tiempos de visualización por nivel (Parejas)
PAREJAS_TIEMPO_VIS = {1: 5, 2: 4, 3: 2}

# Configuración modo Intruso
INTRUSO_CARTAS_POR_NIVEL = 6
INTRUSO_NIVELES_MAX = 5
INTRUSO_PUNTOS_ACIERTO = 10
INTRUSO_PUNTOS_ERROR = -10
INTRUSO_PUNTOS_BONUS = 10
INTRUSO_TIEMPO_ESPERA = 5

# Tiempos de cronómetro por nivel (Intruso)
INTRUSO_TIEMPO_CRONOMETRO = {1: 30, 2: 25, 3: 20, 4: 15, 5: 10}

# Dimensiones de elementos
CARTA_ANCHO = 150
CARTA_ALTO = 200
CARTA_ESPACIADO = 25
MARGEN_CARTAS = 20
CRONOMETRO_ANCHO = 200
CRONOMETRO_ALTO = 80
PUNTUACION_ANCHO = 200
PUNTUACION_ALTO = 80